function mopex = import_mopex(stid)

%% Import data from text file.
% Script for importing data from the following text file:
%
%    /Users/tcmoran/Documents/ENV_DATA/MOPEX/Us_438_Daily/10296000.dly
%
% To extend the code to different selected data or a different text file,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2013/11/26 23:14:25

%% Initialize variables.
id = num2str(stid);
filename = ['/Users/tcmoran/Documents/ENV_DATA/MOPEX/Us_438_Daily/',id,'.dly'];

%% Format string for each line of text:
%   column1: double (%f)
%	column2: double (%f)
%   column3: double (%f)
%	column4: double (%f)
%   column5: double (%f)
%	column6: double (%f)
%   column7: double (%f)
%	column8: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%4f%2f%2f%10f%10f%10f%10f%f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, 'Delimiter', '', 'WhiteSpace', '', 'EmptyValue' ,NaN, 'ReturnOnError', false);

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Create output variable
mopex = [dataArray{1:end-1}];
%% Clear temporary variables
% clearvars filename formatSpec fileID dataArray ans;